### ISSUE TITLE
Wrong nsn result when trying to parse incomplete number of country with leading digits

### ISSUE THREAD

**Issue by cupofme** [cedvdb/phone_numbers_parser#35] opened 2022-12-07 16:11 UTC
When trying to format incomplete numbers for "as-you-type" formatting, some countries produce wrong numbers by adding excess leading number at some stage. I were able to reproduce it only for countries with existing nationalPrefixTransformRule in metadata.

  ## Code to reproduce
  ```dart
import 'package:phone_numbers_parser/phone_numbers_parser.dart';

void main() {
    final fullBermudaNumber = PhoneNumber.parse('+14412957070');
    final incompleteBermudaNumber = PhoneNumber.parse('+14412957');
  
    print(fullBermudaNumber.nsn); // 4412957070 OK
    print(fullBermudaNumber.getFormattedNsn()); // 4412957070 OK
  
    print(incompleteBermudaNumber.nsn); // 4414412957 WRONG (4412957 expected)
    print(incompleteBermudaNumber.getFormattedNsn()); // 4414412957 WRONG (4412957 expected)
  
    final fullUSNumber = PhoneNumber.parse('+14056343023');
    final incompleteUSNumber = PhoneNumber.parse('+14056343');
  
    print(fullUSNumber.nsn); // 4056343023 OK
    print(fullUSNumber.getFormattedNsn()); // 405-634-3023 OK
  
    print(incompleteUSNumber.nsn); // OK
    print(incompleteUSNumber.getFormattedNsn()); // 405-634-3 OK
}

**Comment by cupofme** [comment] 2022-12-08 10:01
@cedvdb Thank you for the quick response! I'll try to implement this fix and make a PR today or tomorrow.

**Comment by cedvdb** [comment] 2022-12-12 22:58
Did you have a stab at it ?

**Comment by cupofme** [comment] 2022-12-13 16:10
Sorry, didn't have enough time to dive deeply into it. Tried to implement [naive fix](https://github.com/cupofme/phone_numbers_parser/commit/a5bb804c6ce90456bb83392b52e7e4c5cf9b2e1e), but it feels obviously wrong and even fails for some regions (mostly British overseas territories)

**Comment by nahimilega** [comment] 2023-01-13 07:29
Hey @cedvdb @cupofme , if possible could you provide an estimated time to fix this bug fix... because I hope you agree it's kinda a major bug..not allowing certain phone numbers.. hampering the business of all the users of the library.

**Comment by cedvdb** [comment] 2023-01-13 15:52
@nahimilega No timeline from me. Feel free to get your hands dirty.

**Comment by blopker** [comment] 2023-02-09 20:29
@cedvdb, first, thanks for this lib, so much better than using all the platform-specific stuff. Does the fix @cupofme made work for you? Happy to make a PR for it if so.

**Comment by cedvdb** [comment] 2023-02-11 12:54
No it did not work as intended, my comment here should give a rough idea of what's going on: https://github.com/cedvdb/phone_numbers_parser/issues/35#issuecomment-1341669974 but I don't think the fix explained is entirely correct as I remember having a quick stab at it.

A PR would very much be appreciated

**Comment by blopker** [comment] 2023-02-11 23:08
I see. Are there a few test cases you could provide that fail, so I know exactly what the issue is? Or is the code in the reproduction a good test?

**Comment by cedvdb** [comment] 2023-02-19 13:48
Fixed in next version

**Closed by cedvdb** 2023-02-19 13:48 UTC
